name: "oopetris-lobby"
services:
  db:
    container_name: oopetris-lobby-db
    image: postgres:17
    restart: unless-stopped
    shm_size: 128mb
    healthcheck:
      test: pg_isready -d oopetris_lobby -U postgres
      interval: 5m
      start_interval: 30s
      start_period: 5s
      retries: 3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=oopetris_lobby
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - "./database:/var/lib/postgresql/data/"
    networks:
      main:
        aliases:
          - db

  backend:
    container_name: oopetris-lobby-backend
    build:
      context: .
      dockerfile: Dockerfiles/backend
      platforms:
        - "linux/amd64"
        - "linux/arm64/v8"
      args:
        # TODO: somehow run "git rev-parse HEAD" here
        - OOPETRIS_LOBBY_COMMIT_HASH=
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:${DATABASE_PASSWORD}@db:5432/oopetris_lobby
    volumes:
      - ./backend_config.json:/app/config.json
    networks:
      main:
        aliases:
          - backend
    ports:
      - 7654:3000
      - 64000-64500:64000-64500

networks:
  main:
