packages:
  - backend
  - frontend
  - shared

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - prisma
  - bcrypt
